services:
  - type: web
    name: mailzap-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STRIPE_SUCCESS_URL
        sync: false
      - key: STRIPE_CANCEL_URL
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: APP_EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false
      - key: GMAIL_REDIRECT_URI
        sync: false
