services:
  - type: web
    name: mailzap-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        value: 1e053a0d6f304f3ee9cc6d616cb9df0b06bb8d3dd75212d3cae359733094bd7b
      - key: ENCRYPTION_KEY
        value: 13f0683dee371efc704196e67ca5db6bfd78a44b5eb0185740f1ac81c5403363
      - key: MAIL_FROM
        value: mkang4636@gmail.com
      - key: MAIL_APP_PASSWORD
        value: chdw eubr oayt tyct
      - key: GROQ_API_KEY
        value: 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
      - key: STRIPE_SECRET_KEY
        value: sk_test_51RdBJ04eD5igLsKL82a2Zcm4BTapJ9sYO2JoB4e7gVNlBrPETTMjnTJEN2yOovcq9QmzcdruXNRZKLIwlz387iFe003JXvhnxw
      - key: STRIPE_PRICE_ID
        value: price_1TjVTg4eD5igLsKLJxSvOGIp
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_8B3ncTNWSDn31BoHERNXWlwlK8MyOOKQ
      - key: STRIPE_SUCCESS_URL
        value: https://server-5bzg.onrender.com/success
      - key: STRIPE_CANCEL_URL
        value: https://server-5bzg.onrender.com/cancel
      - key: BASE_URL
        value: https://server-5bzg.onrender.com
      - key: PORT
        value: "3000"
